sudo: required
language: node_js
env:
  global:
  - VERSION=$TRAVIS_TAG
  - VERSION_COMMIT=$TRAVIS_COMMIT
services:
- docker
node_js:
- 10.13
cache:
  directories:
  - node_modules
notifications:
  email: false
  slack:
    rooms:
      secure: a0k0AogBhCNYGkGlgnmZ3IXtm+V/bgHfbpmqZIbj1QcHe/5QXVRV+64W5x5crvw/UHndbiOBe5f012tChEkf0iD/dT2R3BTiiWmPNq2mDtAXZlf+aL5H61VbcxsfLHuIdNB/EnLwLsPbJg0NJnBocT4+dGUZY40fHS/QyLjJThChqSMRxsu9SLz0fyUHozUQnoIY/3pnbTBzidOaLakbKqQ14xWTuj6hQL3eu5kqPVk5mVYnQGoF/Nx6OqhCFdkSKAjqGod2D307AGQ6hF1jp7riX5T6lw96zXgW/IQ5dKwvz5QrlUSjvaCJEq9o+PpVRPQqC0bDdQjWGKp0Eehv24NrIiQmTzrQxQMvCbTgodbc0XpFyderic7YshdPPSvk3HqTK8KLf1usYL2e+RD9YMS8j6rTWSPLaNhpQfdROGqTkQBV1SmHBcFCQ5fAJBLbw/6cTpI2XRo6+UCz/8ONlDl+d/2TORIpIGTcQv8R2AYgjG2+cmSBlqO3pkGOsT/FXg3h1BBNgsepDPqloAeT2EcvkVpA/+eWY97saYQNT34w+8g89ba128PvbeWrQMkxeqKlmZ5C5FeuljdIsBYdQBlGjlTZdCEr/L891Hj5W/eVnCXsiWF+XTtUrdJVPyJBeYRw6Fd4foZXweLHJRXUB3kvSvwoux8aGBGwtDE8Tpk=
    on_success: never
    on_failure: change
    on_pull_requests: false
before_install:
- npm install -g greenkeeper-lockfile@1
install:
- npm install
- |
  curl -fSL "https://releases.hashicorp.com/terraform/0.11.13/terraform_0.11.13_linux_amd64.zip" -o terraform.zip && \
  echo "5925cd4d81e7d8f42a0054df2aafd66e2ab7408dbed2bd748f0022cfe592f8d2 *terraform.zip" | sha256sum -c - && \
  sudo unzip -d /usr/local/bin/ terraform.zip
before_script:
- npm prune
- greenkeeper-lockfile-update
script:
- |
  npm test && \
  npm run build && \
  npm run docker:test
after_success:
- npm run coveralls
- npm run semantic-release
- |
  ([ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ] || [ -n "$TRAVIS_TAG" ]) && \
  echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin && \
  npm run push
- |
  [ -n "$TRAVIS_TAG" ] && npm run deploy
after_script:
- greenkeeper-lockfile-upload
