language: node_js
node_js:
  - '6.3'
cache:
  directories:
    - node_modules
notifications:
  email: false
before_script:
  - 'npm prune'
after_success:
  - 'npm run coveralls'
  - 'npm run semantic-release'
